coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
comment: off

fixes:
  - "dbatools/::bin/projects/dbatools/dbatools/"

