name: Add PowerShell module to Azure Automation
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  addmodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZAUTO_CREDENTIAL }}"
          enable-AzPSSession: true

      - name: Add the module
        uses: potatoqualitee/azautomodule@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_PAT }}
        with:
          resource-group-name: azautomation
          automation-account-name: import-tester