name: Check repo size
on: [pull_request]

jobs:
  clone:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: jwalton/gh-find-current-pr@v1
      - name: Repository size should be less than 90MB
        shell: pwsh
        run: |
          cd /tmp
          gh repo clone dataplat/dbatools
          cd /tmp/dbatools
          Write-Output "Checking out ${PR}"
          gh pr checkout ${PR}
          $objects = git count-objects -v
          $sizepack = $objects -split '`n' | Where-Object { $PSItem -match "size-pack" }
          $size = $sizepack -split " " | Select-Object -Last 1
          Write-Output "Repo size is $size"
          # old size = 110299 or 250000+
          if ($size -gt 95000) { # Size is 89836, so 95000 should last a while
            throw "This clone is outdated. Please reclone your repo and resubmit with the slimmed down repo. See https://github.com/dataplat/dbatools/pull/8637 for more information."
          }
