name: Run Cross Platform Tests
on: [push]
defaults:
  run:
    shell: pwsh
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v2

      - name:  Setup docker images
        run: |
          # create a shared network
          docker network create localnet
          # create a shared volume
          $dir = New-Item -Type Directory $home\Documents\sqlshared -Force -ErrorAction SilentlyContinue
          docker run -p 1433:1433 --network localnet  --volume "$($dir):/sharedpath" --name dockersql1 -d dbatools/sqlinstance
          docker run -p 14333:1433 --network localnet --volume "$($dir):/sharedpath" --name dockersql2 -d dbatools/sqlinstance2

      - name: 👥 Clone appveyor repo
        working-directory: /tmp
        run: |
          gh repo clone sqlcollaborative/appveyor-lab

      - name: Run tests
        env:
          TENANTID: ${{secrets.TENANTID}}
          CLIENTID: ${{secrets.CLIENTID}}
          CLIENTSECRET: ${{secrets.CLIENTSECRET}}
        run: |
          $results = Invoke-Pester ./tests/gh-actions.ps1 -Output Detailed -PassThru
          Get-DbatoolsError -All
          if ($results.Result -ne "Passed") {
              throw "There were $($results.FailedCount) failed tests."
          }