name: Run Cross Platform Tests
on: [push]
defaults:
  run:
    shell: pwsh
jobs:
  linux-tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v2

      - name:  Setup docker images
        run: |
          # create a shared network
          docker network create localnet
          # Expose engine and endpoint then setup a shared path for migrations
          docker run -p 1433:1433  --volume shared:/shared:z --name mssql1 --hostname mssql1 --network localnet -d dbatools/sqlinstance
          # Expose second engine and endpoint on different port
          docker run -p 14333:1433 --volume shared:/shared:z --name mssql2 --hostname mssql2 --network localnet -d dbatools/sqlinstance2

      - name: 👥 Clone appveyor repo
        working-directory: /tmp
        run: |
          gh repo clone sqlcollaborative/appveyor-lab

      - name: Run tests
        env:
          TENANTID: ${{secrets.TENANTID}}
          CLIENTID: ${{secrets.CLIENTID}}
          CLIENTSECRET: ${{secrets.CLIENTSECRET}}
        run: $null = Invoke-Pester ./tests/gh-actions.ps1 -Output Detailed -PassThru

  windows-tests:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v2

      - name: Install SQL Server
        uses: potatoqualitee/mssqlsuite@v1.3
        with:
          install: localdb

      - name: Create localdb instance
        run: |
          sqllocaldb create dbatools
          Import-Module ./dbatools.psm1 -Force
          Connect-DbaInstance -SqlInstance "(localdb)\dbatools"

      - name: Run PowerShell tests
        env:
          TENANTID: ${{secrets.TENANTID}}
          CLIENTID: ${{secrets.CLIENTID}}
          CLIENTSECRET: ${{secrets.CLIENTSECRET}}
        shell: powershell
        run: $null = Invoke-Pester ./tests/gh-winactions.ps1 -Output Detailed -PassThru

      - name: Run pwsh tests
        env:
          TENANTID: ${{secrets.TENANTID}}
          CLIENTID: ${{secrets.CLIENTID}}
          CLIENTSECRET: ${{secrets.CLIENTSECRET}}
        shell: pwsh
        run: $null = Invoke-Pester ./tests/gh-winactions.ps1 -Output Detailed -PassThru