name: Cross Platform Import
on: [push]
defaults:
  env:
    SMODefaultModuleName: dbatools

jobs:
  build:
    env:
      SMODefaultModuleName: dbatools
    name: Module imports on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest, arm64]

    steps:
    - uses: actions/checkout@v3

    - name: Install and cache PowerShell modules
      uses: potatoqualitee/psmodulecache@v5.2
      with:
          modules-to-cache: dbatools.library:2023.5.5

    - name: Perform the import
      shell: pwsh
      run: |
        Import-Module ./dbatools.psd1 -ErrorAction Stop
        (Get-DbaManagementObject).LoadTemplate -ne $null