name: Cross Platform Import
on: [push]

jobs:
  build:
    name: Module imports on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install and cache PowerShell modules
      uses: potatoqualitee/psmodulecache@v5.1
      with:
        modules-to-cache: dbatools.core.library:2022.11.8
        modules-to-cache-prerelease: dbatools.library:2022.11.8-preview

    - name: Perform the import
      shell: pwsh
      run: |
        Import-Module ./dbatools.psd1 -ErrorAction Stop
        (Get-DbaManagementObject).LoadTemplate -ne $null